-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 08, 2024 at 05:37 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tickets`
--

-- --------------------------------------------------------

--
-- Table structure for table `tickets`
--

CREATE TABLE `tickets` (
  `id` int(11) NOT NULL,
  `issue_description` text NOT NULL,
  `priority` varchar(6) NOT NULL,
  `assigned_to` varchar(50) NOT NULL,
  `status` varchar(11) NOT NULL,
  `created_date` date NOT NULL,
  `resolved_date` date NOT NULL,
  `estimated_duration_hours` int(11) NOT NULL,
  `actual_duration_hours` int(11) NOT NULL,
  `category` varchar(14) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tickets`
--

INSERT INTO `tickets` (`id`, `issue_description`, `priority`, `assigned_to`, `status`, `created_date`, `resolved_date`, `estimated_duration_hours`, `actual_duration_hours`, `category`) VALUES
(1, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Low', 'Luisa Caulliere', 'Resolved', '0000-00-00', '0000-00-00', 6, 10, 'Network Issue'),
(2, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Medium', 'Tome Nairns', 'Open', '0000-00-00', '0000-00-00', 16, 10, 'Hardware Issue'),
(3, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'High', 'Noland Faircliffe', 'Open', '0000-00-00', '0000-00-00', 3, 8, 'Network Issue'),
(4, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Medium', 'Emiline Longford', 'Open', '0000-00-00', '0000-00-00', 23, 15, 'User Issue'),
(5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'Low', 'Noah McEnteggart', 'Open', '0000-00-00', '0000-00-00', 5, 24, 'Software Issue'),
(6, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Medium', 'Giorgi Schafer', 'Open', '0000-00-00', '0000-00-00', 8, 3, 'Hardware Issue'),
(7, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Low', 'Kelcy Basindale', 'In Progress', '0000-00-00', '0000-00-00', 11, 1, 'Hardware Issue'),
(8, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Low', 'Rob Mycock', 'In Progress', '0000-00-00', '0000-00-00', 22, 1, 'Software Issue'),
(9, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'High', 'Easter Cleare', 'Open', '0000-00-00', '0000-00-00', 1, 23, 'Hardware Issue'),
(10, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Low', 'Shea Seadon', 'Resolved', '0000-00-00', '0000-00-00', 1, 5, 'Hardware Issue'),
(11, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Low', 'Bunni Leall', 'In Progress', '0000-00-00', '0000-00-00', 12, 2, 'Software Issue'),
(12, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'High', 'Mill Shillaker', 'Open', '0000-00-00', '0000-00-00', 24, 17, 'Network Issue'),
(13, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\r\n\r\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Medium', 'Scottie Hullyer', 'Open', '0000-00-00', '0000-00-00', 23, 17, 'User Issue'),
(14, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'High', 'Marie Toffolo', 'Resolved', '0000-00-00', '0000-00-00', 15, 7, 'Hardware Issue'),
(15, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Medium', 'Delores Hessing', 'Resolved', '0000-00-00', '0000-00-00', 16, 21, 'Hardware Issue'),
(16, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'Medium', 'Wendy Cumber', 'In Progress', '0000-00-00', '0000-00-00', 22, 22, 'Software Issue'),
(17, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'High', 'Inge Fender', 'In Progress', '0000-00-00', '0000-00-00', 17, 23, 'User Issue'),
(18, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'High', 'Luther Couch', 'In Progress', '0000-00-00', '0000-00-00', 7, 4, 'User Issue'),
(19, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'High', 'Darlene Patington', 'Open', '0000-00-00', '0000-00-00', 14, 14, 'Software Issue'),
(20, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'High', 'Ashleigh Swainson', 'In Progress', '0000-00-00', '0000-00-00', 16, 12, 'Software Issue'),
(21, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Low', 'Vera Bragg', 'Resolved', '0000-00-00', '0000-00-00', 19, 2, 'Network Issue'),
(22, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Medium', 'Gypsy Cheves', 'Open', '0000-00-00', '0000-00-00', 24, 13, 'User Issue'),
(23, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Low', 'Melvin Rablen', 'Resolved', '0000-00-00', '0000-00-00', 5, 19, 'Software Issue'),
(24, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Medium', 'Novelia Shearston', 'Resolved', '0000-00-00', '0000-00-00', 8, 11, 'Network Issue'),
(25, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Low', 'Danika Kubecka', 'Open', '0000-00-00', '0000-00-00', 12, 15, 'Network Issue'),
(26, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Low', 'Webb Pittet', 'Resolved', '0000-00-00', '0000-00-00', 13, 20, 'Software Issue'),
(27, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Medium', 'Kelwin Di Roberto', 'In Progress', '0000-00-00', '0000-00-00', 18, 13, 'Software Issue'),
(28, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n\r\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'High', 'Mahalia Dulany', 'Resolved', '0000-00-00', '0000-00-00', 11, 5, 'Software Issue'),
(29, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Low', 'Mort Kirk', 'In Progress', '0000-00-00', '0000-00-00', 2, 4, 'Software Issue'),
(30, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'High', 'Saxon Carletto', 'Resolved', '0000-00-00', '0000-00-00', 3, 17, 'Hardware Issue'),
(31, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Low', 'Ronald Cafferty', 'Resolved', '0000-00-00', '0000-00-00', 1, 16, 'Hardware Issue'),
(32, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'High', 'Oralla Dykins', 'In Progress', '0000-00-00', '0000-00-00', 13, 14, 'Network Issue'),
(33, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.', 'High', 'Mikol Brosel', 'Open', '0000-00-00', '0000-00-00', 21, 12, 'Software Issue'),
(34, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Medium', 'Florenza Nicklinson', 'In Progress', '0000-00-00', '0000-00-00', 24, 4, 'Hardware Issue'),
(35, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Medium', 'Killian Kincey', 'Resolved', '0000-00-00', '0000-00-00', 4, 4, 'User Issue'),
(36, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Low', 'Davy Hurch', 'In Progress', '0000-00-00', '0000-00-00', 3, 6, 'User Issue'),
(37, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Medium', 'Fairfax Langman', 'In Progress', '0000-00-00', '0000-00-00', 2, 5, 'Software Issue'),
(38, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Medium', 'Merrielle Luchetti', 'In Progress', '0000-00-00', '0000-00-00', 9, 11, 'User Issue'),
(39, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n\r\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Low', 'Katharyn Crosseland', 'Resolved', '0000-00-00', '0000-00-00', 4, 15, 'Hardware Issue'),
(40, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'High', 'Sissie Craik', 'Open', '0000-00-00', '0000-00-00', 3, 12, 'Network Issue'),
(41, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'High', 'Zandra Killingbeck', 'In Progress', '0000-00-00', '0000-00-00', 1, 12, 'Software Issue'),
(42, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'High', 'Theodosia Letherbury', 'Resolved', '0000-00-00', '0000-00-00', 2, 4, 'Hardware Issue'),
(43, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'High', 'Cleveland Boyall', 'Open', '0000-00-00', '0000-00-00', 12, 18, 'Network Issue'),
(44, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Medium', 'Cristobal Hadye', 'In Progress', '0000-00-00', '0000-00-00', 1, 18, 'Network Issue'),
(45, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Low', 'Lief Hawford', 'Resolved', '0000-00-00', '0000-00-00', 3, 12, 'Hardware Issue'),
(46, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Low', 'Michel Flaherty', 'In Progress', '0000-00-00', '0000-00-00', 7, 10, 'User Issue'),
(47, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Medium', 'Michel Pothbury', 'Open', '0000-00-00', '0000-00-00', 17, 16, 'Network Issue'),
(48, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Medium', 'Noella O\'Hannen', 'Open', '0000-00-00', '0000-00-00', 10, 17, 'Software Issue'),
(49, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Medium', 'Reinaldo MacCumeskey', 'Open', '0000-00-00', '0000-00-00', 10, 19, 'Hardware Issue'),
(50, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Medium', 'Bride Callington', 'In Progress', '0000-00-00', '0000-00-00', 17, 15, 'Hardware Issue'),
(51, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'High', 'Jori Pomeroy', 'In Progress', '0000-00-00', '0000-00-00', 4, 5, 'Network Issue'),
(52, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Medium', 'Pren Cloney', 'In Progress', '0000-00-00', '0000-00-00', 23, 1, 'Software Issue'),
(53, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'High', 'Phedra Krolik', 'Open', '0000-00-00', '0000-00-00', 12, 16, 'Software Issue'),
(54, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'High', 'Guenevere Hedaux', 'Open', '0000-00-00', '0000-00-00', 19, 20, 'Network Issue'),
(55, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Low', 'Giacinta Gregoratti', 'Open', '0000-00-00', '0000-00-00', 23, 8, 'User Issue'),
(56, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'High', 'Aubrette Uden', 'In Progress', '0000-00-00', '0000-00-00', 23, 1, 'User Issue'),
(57, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Low', 'Corena Humphrys', 'Resolved', '0000-00-00', '0000-00-00', 16, 14, 'User Issue'),
(58, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'High', 'Melli Beccero', 'In Progress', '0000-00-00', '0000-00-00', 2, 19, 'Network Issue'),
(59, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'High', 'Carter Temperley', 'Resolved', '0000-00-00', '0000-00-00', 3, 16, 'User Issue'),
(60, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Low', 'Abbie Arnet', 'Resolved', '0000-00-00', '0000-00-00', 3, 20, 'Network Issue'),
(61, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Medium', 'Ricki Cribbin', 'Resolved', '0000-00-00', '0000-00-00', 2, 8, 'User Issue'),
(62, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'High', 'Ardath Tranckle', 'Open', '0000-00-00', '0000-00-00', 7, 19, 'Network Issue'),
(63, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.', 'Medium', 'Cash Lyptratt', 'In Progress', '0000-00-00', '0000-00-00', 11, 3, 'User Issue'),
(64, 'In congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Medium', 'Godfree Hayball', 'In Progress', '0000-00-00', '0000-00-00', 5, 9, 'User Issue'),
(65, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Medium', 'Kessiah Allinson', 'Open', '0000-00-00', '0000-00-00', 7, 19, 'Network Issue'),
(66, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Low', 'Pearla Halden', 'In Progress', '0000-00-00', '0000-00-00', 22, 24, 'Hardware Issue'),
(67, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Medium', 'Marielle Tommei', 'Open', '0000-00-00', '0000-00-00', 19, 19, 'User Issue'),
(68, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'High', 'Urson Reame', 'In Progress', '0000-00-00', '0000-00-00', 17, 14, 'Software Issue'),
(69, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'High', 'Marlee Shillam', 'In Progress', '0000-00-00', '0000-00-00', 23, 9, 'Software Issue'),
(70, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Low', 'Adriane Jubert', 'Resolved', '0000-00-00', '0000-00-00', 7, 24, 'Network Issue'),
(71, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'High', 'Gunar Dinesen', 'In Progress', '0000-00-00', '0000-00-00', 23, 10, 'Software Issue'),
(72, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Low', 'Jewelle Dumke', 'Resolved', '0000-00-00', '0000-00-00', 5, 7, 'User Issue'),
(73, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'High', 'Salvidor Carthew', 'Resolved', '0000-00-00', '0000-00-00', 3, 14, 'Software Issue'),
(74, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Low', 'Raff Pitone', 'Open', '0000-00-00', '0000-00-00', 5, 3, 'Network Issue'),
(75, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'High', 'Bendick Stit', 'Resolved', '0000-00-00', '0000-00-00', 13, 5, 'Hardware Issue'),
(76, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'High', 'Claudine Glassopp', 'In Progress', '0000-00-00', '0000-00-00', 17, 24, 'User Issue'),
(77, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'High', 'Doreen Smerdon', 'Resolved', '0000-00-00', '0000-00-00', 14, 24, 'Network Issue'),
(78, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Low', 'Jay Wattinham', 'In Progress', '0000-00-00', '0000-00-00', 19, 21, 'Network Issue'),
(79, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Low', 'Donnell Earp', 'In Progress', '0000-00-00', '0000-00-00', 22, 9, 'Software Issue'),
(80, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Medium', 'Barbra Krauze', 'Open', '0000-00-00', '0000-00-00', 15, 7, 'Hardware Issue'),
(81, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Low', 'Toddy Davioud', 'Open', '0000-00-00', '0000-00-00', 13, 5, 'Hardware Issue'),
(82, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Low', 'Alice Reader', 'Resolved', '0000-00-00', '0000-00-00', 23, 20, 'User Issue'),
(83, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Medium', 'Gabriele Mabbitt', 'In Progress', '0000-00-00', '0000-00-00', 6, 4, 'Network Issue'),
(84, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'High', 'Lief Margerrison', 'Open', '0000-00-00', '0000-00-00', 9, 12, 'User Issue'),
(85, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Medium', 'Rania Spurman', 'In Progress', '0000-00-00', '0000-00-00', 18, 22, 'Network Issue'),
(86, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'High', 'Siana Hiner', 'Open', '0000-00-00', '0000-00-00', 12, 8, 'Network Issue'),
(87, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Medium', 'Tallou Jeandot', 'Resolved', '0000-00-00', '0000-00-00', 4, 9, 'User Issue'),
(88, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Low', 'Ric Flukes', 'In Progress', '0000-00-00', '0000-00-00', 5, 19, 'Network Issue'),
(89, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'High', 'Dana Liffe', 'Open', '0000-00-00', '0000-00-00', 16, 15, 'Network Issue'),
(90, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Low', 'Jamima Brumham', 'In Progress', '0000-00-00', '0000-00-00', 9, 19, 'Software Issue'),
(91, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'High', 'Derick Venny', 'Open', '0000-00-00', '0000-00-00', 19, 1, 'Network Issue'),
(92, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'High', 'Lulu Lillecrop', 'In Progress', '0000-00-00', '0000-00-00', 20, 16, 'Software Issue'),
(93, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Medium', 'Timotheus Flux', 'Open', '0000-00-00', '0000-00-00', 22, 19, 'Software Issue'),
(94, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Medium', 'Benny Dauber', 'Resolved', '0000-00-00', '0000-00-00', 11, 11, 'User Issue'),
(95, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Medium', 'Cthrine Delmage', 'Open', '0000-00-00', '0000-00-00', 14, 17, 'Network Issue'),
(96, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'High', 'Marice Harries', 'Resolved', '0000-00-00', '0000-00-00', 18, 21, 'Hardware Issue'),
(97, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Low', 'Angelia Jowsey', 'In Progress', '0000-00-00', '0000-00-00', 14, 1, 'Software Issue'),
(98, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'High', 'Sharline Dilley', 'Open', '0000-00-00', '0000-00-00', 24, 17, 'Hardware Issue'),
(99, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Low', 'Oates Kulicke', 'Resolved', '0000-00-00', '0000-00-00', 13, 5, 'Hardware Issue'),
(100, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Medium', 'Fanni Hakonsson', 'Open', '0000-00-00', '0000-00-00', 16, 19, 'Network Issue'),
(101, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Medium', 'Danice Twist', 'In Progress', '0000-00-00', '0000-00-00', 18, 12, 'Hardware Issue'),
(102, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Low', 'Geoff Markushkin', 'Resolved', '0000-00-00', '0000-00-00', 23, 5, 'Network Issue'),
(103, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'High', 'Putnam Tregidgo', 'Open', '0000-00-00', '0000-00-00', 7, 17, 'Network Issue'),
(104, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'High', 'Allister Garfitt', 'In Progress', '0000-00-00', '0000-00-00', 10, 8, 'Network Issue'),
(105, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.', 'Low', 'Tessi Sinney', 'Open', '0000-00-00', '0000-00-00', 5, 13, 'Hardware Issue'),
(106, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'High', 'Eugene Jumel', 'Open', '0000-00-00', '0000-00-00', 22, 13, 'Software Issue'),
(107, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.', 'High', 'Schuyler Jindrak', 'Open', '0000-00-00', '0000-00-00', 1, 24, 'Software Issue'),
(108, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Medium', 'Marjie Blunsen', 'Resolved', '0000-00-00', '0000-00-00', 15, 16, 'User Issue'),
(109, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Low', 'Elsbeth Birk', 'Open', '0000-00-00', '0000-00-00', 2, 17, 'Software Issue'),
(110, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Medium', 'Thalia Gambles', 'Resolved', '0000-00-00', '0000-00-00', 20, 21, 'User Issue'),
(111, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Low', 'Caroljean Blackstock', 'Open', '0000-00-00', '0000-00-00', 17, 20, 'Network Issue'),
(112, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Low', 'Elenore Vaughan-Hughes', 'In Progress', '0000-00-00', '0000-00-00', 13, 2, 'Network Issue'),
(113, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.', 'Medium', 'Inger Royden', 'In Progress', '0000-00-00', '0000-00-00', 11, 23, 'User Issue'),
(114, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'High', 'Karoly Churm', 'Open', '0000-00-00', '0000-00-00', 2, 2, 'Hardware Issue'),
(115, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Low', 'Dido Slark', 'In Progress', '0000-00-00', '0000-00-00', 8, 10, 'User Issue'),
(116, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Medium', 'Leilah Schuster', 'In Progress', '0000-00-00', '0000-00-00', 4, 3, 'User Issue'),
(117, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Low', 'Chilton Balaison', 'In Progress', '0000-00-00', '0000-00-00', 6, 18, 'Network Issue'),
(118, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'High', 'Ede Flemming', 'In Progress', '0000-00-00', '0000-00-00', 14, 6, 'Software Issue'),
(119, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Medium', 'Regan Hekkert', 'Resolved', '0000-00-00', '0000-00-00', 7, 3, 'Hardware Issue'),
(120, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Low', 'Mil Drillot', 'Resolved', '0000-00-00', '0000-00-00', 4, 19, 'Software Issue'),
(121, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'High', 'Susana Brummitt', 'Resolved', '0000-00-00', '0000-00-00', 16, 23, 'Software Issue'),
(122, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'Medium', 'Fay Dowbekin', 'In Progress', '0000-00-00', '0000-00-00', 20, 3, 'Software Issue'),
(123, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Low', 'Anabella Kinge', 'In Progress', '0000-00-00', '0000-00-00', 13, 14, 'Software Issue'),
(124, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'High', 'Scotti Bow', 'Open', '0000-00-00', '0000-00-00', 21, 2, 'User Issue'),
(125, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Medium', 'Florry Stinson', 'In Progress', '0000-00-00', '0000-00-00', 9, 4, 'Software Issue'),
(126, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Medium', 'Chev Scutching', 'In Progress', '0000-00-00', '0000-00-00', 23, 7, 'Network Issue'),
(127, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Medium', 'Lyndsie Wadsworth', 'Resolved', '0000-00-00', '0000-00-00', 15, 18, 'User Issue'),
(128, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'High', 'Caldwell McCart', 'Open', '0000-00-00', '0000-00-00', 18, 22, 'Network Issue'),
(129, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Low', 'Yorgos Massimo', 'In Progress', '0000-00-00', '0000-00-00', 19, 13, 'Hardware Issue'),
(130, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Low', 'Filippa Bosworth', 'Resolved', '0000-00-00', '0000-00-00', 18, 6, 'Software Issue'),
(131, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Medium', 'Rachel Maroney', 'Resolved', '0000-00-00', '0000-00-00', 23, 16, 'User Issue'),
(132, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Low', 'Kele Radenhurst', 'Open', '0000-00-00', '0000-00-00', 7, 13, 'Network Issue'),
(133, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Medium', 'Ketti Hefner', 'Resolved', '0000-00-00', '0000-00-00', 3, 17, 'Network Issue'),
(134, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Medium', 'Adiana Moring', 'Resolved', '0000-00-00', '0000-00-00', 16, 21, 'Hardware Issue'),
(135, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.', 'Low', 'Garald Snap', 'In Progress', '0000-00-00', '0000-00-00', 3, 1, 'User Issue'),
(136, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Low', 'Celine Tubb', 'Resolved', '0000-00-00', '0000-00-00', 24, 1, 'Hardware Issue'),
(137, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'High', 'Mathew Choudhury', 'Open', '0000-00-00', '0000-00-00', 6, 4, 'User Issue'),
(138, 'Fusce consequat. Nulla nisl. Nunc nisl.', 'High', 'Kathi Sparrowe', 'Resolved', '0000-00-00', '0000-00-00', 19, 24, 'Hardware Issue'),
(139, 'In congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Medium', 'Mattie Manclark', 'In Progress', '0000-00-00', '0000-00-00', 23, 20, 'User Issue'),
(140, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'High', 'Tarah Vassman', 'In Progress', '0000-00-00', '0000-00-00', 12, 6, 'User Issue'),
(141, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Low', 'Ken Kantor', 'Resolved', '0000-00-00', '0000-00-00', 4, 8, 'Network Issue'),
(142, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Medium', 'Fleur Wreak', 'Resolved', '0000-00-00', '0000-00-00', 17, 13, 'Hardware Issue'),
(143, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Low', 'Zora Buttwell', 'In Progress', '0000-00-00', '0000-00-00', 24, 4, 'User Issue');
INSERT INTO `tickets` (`id`, `issue_description`, `priority`, `assigned_to`, `status`, `created_date`, `resolved_date`, `estimated_duration_hours`, `actual_duration_hours`, `category`) VALUES
(144, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Medium', 'Amalia Blay', 'In Progress', '0000-00-00', '0000-00-00', 3, 9, 'Hardware Issue'),
(145, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Low', 'Billy Chicchelli', 'Resolved', '0000-00-00', '0000-00-00', 8, 23, 'Network Issue'),
(146, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'High', 'Kara-lynn Stringman', 'In Progress', '0000-00-00', '0000-00-00', 1, 2, 'Software Issue'),
(147, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Medium', 'Kathie Rowlatt', 'In Progress', '0000-00-00', '0000-00-00', 17, 15, 'Network Issue'),
(148, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Low', 'Gareth Clampe', 'Resolved', '0000-00-00', '0000-00-00', 15, 23, 'Software Issue'),
(149, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'High', 'Barbaraanne Vaar', 'Open', '0000-00-00', '0000-00-00', 21, 6, 'User Issue'),
(150, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Low', 'Charis Rudeforth', 'In Progress', '0000-00-00', '0000-00-00', 20, 12, 'User Issue'),
(151, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Medium', 'Cecil Sleightholm', 'In Progress', '0000-00-00', '0000-00-00', 7, 20, 'Hardware Issue'),
(152, 'In congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Low', 'Sebastien Longland', 'Resolved', '0000-00-00', '0000-00-00', 3, 19, 'Software Issue'),
(153, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Medium', 'Nolie Balcers', 'Open', '0000-00-00', '0000-00-00', 22, 15, 'Software Issue'),
(154, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Low', 'Carmelia Raikes', 'Open', '0000-00-00', '0000-00-00', 1, 23, 'Software Issue'),
(155, 'Fusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Medium', 'Blayne Boycott', 'In Progress', '0000-00-00', '0000-00-00', 23, 21, 'User Issue'),
(156, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\r\n\r\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'High', 'Cornelia Hember', 'In Progress', '0000-00-00', '0000-00-00', 23, 12, 'Network Issue'),
(157, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Medium', 'Corena Cristou', 'In Progress', '0000-00-00', '0000-00-00', 14, 5, 'Network Issue'),
(158, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Medium', 'Jackie Radoux', 'Open', '0000-00-00', '0000-00-00', 6, 23, 'User Issue'),
(159, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\r\n\r\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Medium', 'Pietro Bruhnicke', 'Open', '0000-00-00', '0000-00-00', 13, 18, 'Hardware Issue'),
(160, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Low', 'Olga Fairholme', 'In Progress', '0000-00-00', '0000-00-00', 17, 13, 'Software Issue'),
(161, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'High', 'Elianora Ullyatt', 'Open', '0000-00-00', '0000-00-00', 1, 2, 'Network Issue'),
(162, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'High', 'Hector Ever', 'In Progress', '0000-00-00', '0000-00-00', 11, 16, 'Network Issue'),
(163, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Low', 'Malorie Milazzo', 'Open', '0000-00-00', '0000-00-00', 17, 13, 'User Issue'),
(164, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'High', 'Arlan Corbridge', 'Open', '0000-00-00', '0000-00-00', 14, 7, 'Hardware Issue'),
(165, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'High', 'Roi Whithorn', 'In Progress', '0000-00-00', '0000-00-00', 14, 4, 'Software Issue'),
(166, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Low', 'Janetta Selvester', 'Open', '0000-00-00', '0000-00-00', 12, 24, 'Hardware Issue'),
(167, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Medium', 'Mariejeanne Inder', 'In Progress', '0000-00-00', '0000-00-00', 14, 13, 'Network Issue'),
(168, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'High', 'Melitta Lambertson', 'Resolved', '0000-00-00', '0000-00-00', 2, 3, 'Software Issue'),
(169, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Low', 'Brocky Willatts', 'Resolved', '0000-00-00', '0000-00-00', 11, 17, 'User Issue'),
(170, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'High', 'Clevey Gravells', 'Resolved', '0000-00-00', '0000-00-00', 18, 1, 'Network Issue'),
(171, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'High', 'Annadiana Ahrend', 'Resolved', '0000-00-00', '0000-00-00', 22, 4, 'Network Issue'),
(172, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Low', 'Vernice Zipsell', 'Resolved', '0000-00-00', '0000-00-00', 15, 15, 'Network Issue'),
(173, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Medium', 'Randene Staning', 'In Progress', '0000-00-00', '0000-00-00', 16, 17, 'Software Issue'),
(174, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'High', 'Merridie Honeywood', 'Resolved', '0000-00-00', '0000-00-00', 1, 12, 'User Issue'),
(175, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Medium', 'Rebecka Kesterton', 'In Progress', '0000-00-00', '0000-00-00', 3, 22, 'User Issue'),
(176, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Low', 'Angelique Borne', 'In Progress', '0000-00-00', '0000-00-00', 24, 4, 'Software Issue'),
(177, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.', 'High', 'Ursuline Pacquet', 'Open', '0000-00-00', '0000-00-00', 8, 1, 'User Issue'),
(178, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'High', 'Davina Krauss', 'In Progress', '0000-00-00', '0000-00-00', 14, 4, 'User Issue'),
(179, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'High', 'Northrup Hubbocks', 'In Progress', '0000-00-00', '0000-00-00', 6, 6, 'Network Issue'),
(180, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Medium', 'Natala Tretwell', 'Resolved', '0000-00-00', '0000-00-00', 13, 4, 'Software Issue'),
(181, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Medium', 'Benita Hodjetts', 'Open', '0000-00-00', '0000-00-00', 21, 8, 'User Issue'),
(182, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Low', 'Beck Gonsalo', 'In Progress', '0000-00-00', '0000-00-00', 6, 9, 'Network Issue'),
(183, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Medium', 'Garek Birkbeck', 'Resolved', '0000-00-00', '0000-00-00', 1, 1, 'Hardware Issue'),
(184, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Medium', 'Merrick Gronno', 'In Progress', '0000-00-00', '0000-00-00', 19, 12, 'User Issue'),
(185, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Low', 'Darice Wroth', 'Open', '0000-00-00', '0000-00-00', 12, 23, 'Hardware Issue'),
(186, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\r\n\r\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Low', 'Ashly Skillicorn', 'Resolved', '0000-00-00', '0000-00-00', 19, 24, 'Network Issue'),
(187, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Medium', 'Reeba Stonehewer', 'In Progress', '0000-00-00', '0000-00-00', 15, 22, 'User Issue'),
(188, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'High', 'Koren Rubenfeld', 'In Progress', '0000-00-00', '0000-00-00', 13, 9, 'User Issue'),
(189, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Medium', 'Angelico Linskill', 'Resolved', '0000-00-00', '0000-00-00', 6, 10, 'Hardware Issue'),
(190, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Low', 'Maxy Tommis', 'Open', '0000-00-00', '0000-00-00', 1, 1, 'User Issue'),
(191, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Low', 'Gill Vasiliu', 'Resolved', '0000-00-00', '0000-00-00', 21, 11, 'Software Issue'),
(192, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'High', 'Stephanus Petworth', 'Resolved', '0000-00-00', '0000-00-00', 15, 1, 'User Issue'),
(193, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Low', 'Tally Kleinhandler', 'Resolved', '0000-00-00', '0000-00-00', 3, 20, 'User Issue'),
(194, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'High', 'Maxi Camellini', 'In Progress', '0000-00-00', '0000-00-00', 3, 2, 'User Issue'),
(195, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Low', 'Clerc McMickan', 'Resolved', '0000-00-00', '0000-00-00', 1, 12, 'Software Issue'),
(196, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.', 'High', 'Ruy Bernardeau', 'In Progress', '0000-00-00', '0000-00-00', 4, 13, 'Network Issue'),
(197, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'High', 'Lusa Morot', 'Open', '0000-00-00', '0000-00-00', 6, 7, 'User Issue'),
(198, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Medium', 'Christye Neave', 'In Progress', '0000-00-00', '0000-00-00', 22, 20, 'Network Issue'),
(199, 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Medium', 'Barnett Van Velde', 'In Progress', '0000-00-00', '0000-00-00', 14, 21, 'Software Issue'),
(200, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Medium', 'Randee Gianulli', 'Open', '0000-00-00', '0000-00-00', 2, 4, 'User Issue');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tickets`
--
ALTER TABLE `tickets`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tickets`
--
ALTER TABLE `tickets`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=201;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
